include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_unused_constructor_parameters
    - always_declare_return_types
    - always_put_control_body_on_new_line
    - require_trailing_commas
    - avoid_print
    - avoid_returning_null_for_void
