name: oui
description: "UI Components for Flutter you want to say 'Oui!' to."
version: 1.0.0
homepage: github.com/onezerocompany/oui

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=4.0.0 <6.0.0"
  test: ^1.25.7
  coverage: ^1.0.3

flutter:
  assets:
    - fonts/
